name: Create Document issue for Merge Request

# Run this action when we merge into master
on:
  push:
    branches:
      - master

jobs:
  # Create an issue on the documentation repository to document whatever was just pulled in.
  create-doc-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create an issue on the documentation repository
        run: |
          TITLE=$(git log --oneline | head -n 1 | cut -d' ' -f2-)
          BODY="{
           \"title\": \"OOD PR $TITLE\",
           \"body\": \"Create documentation for https://github.com/OSC/ondemand/commit/$GITHUB_SHA\"
          }"

          echo $TITLE
          echo $BODY

          curl -v --user johrstrom --request POST \
          --url https://api.github.com/repos/johrstrom/other-test-actions/issues \
          --header 'Authorization: token ${{ secrets.MY_TOKEN }}' \
          --header 'content-type: application/json' \
          --data "$BODY"

